mstorsjo/llvm-mingw

- build-mingw-w64.sh
This version has stubs for RtlCaptureContext which allows using SEH for
windows store
> Bump mingw-w64 hash

- run-tests.sh
The variable is named similar to `RUN_ARMV7` and `RUN_AARCH64`
> tests: don't run using wine on mingw

- wrappers/native-wrapper.h
I was seeing random crashes using the latest revision.
The array allocated in _tspawnvp_escape was too small to contain the terminating NULL.
> Fix out of bound array access in native-wrappers.h

- wrappers/dlltool-wrapper.sh
- wrappers/ld-wrapper.sh
- wrappers/objdump-wrapper.sh
I have some issues compiling in WSL because of that.
> wrappers: fix PATH not working when there are spaces in them

- README.md
`pacman -S` by default reinstalls (and redownloads if necessary) packages given as arguments. Adding `--needed` flag makes it skip packages which are already installed and up to date.
> Update MSYS2 instructions

- wrappers/clang-target-wrapper.c
- wrappers/clang-target-wrapper.sh
- wrappers/ld-wrapper.sh
- windowsapp is the preferred library when targeting Windows 10, it's safe to use it with the current mingw-w64 repo
https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis
- ucrtbase.dll is the DLL that holds the equivalent of what was in vcruntime140_app
- `__MSVCRT_VERSION__` ensures we use the Universal C runtime
> Update the mingw32uwp wrapper libraries

- build-mingw-w64.sh
git port is typically blocked by outbound corporate firewalls.
> build-mingw-w64: Clone on https instead of git protocol

- Dockerfile
- Dockerfile.dev
- README.md
- build-all.sh
- build-libssp.sh
svn is typically blocked on corporate firewalls.
> libssp: Download directory from gitlab instead of svn

- wrappers/windres-wrapper.c
modified:   wrappers/windres-wrapper.c - print_version now passes 0 to exit function. According to @ruki at xmake, the GNU windres program returns zero when `--version` is called.
> Update `windres-wrapper --version` to return 0

- build-mingw-w64.sh
SourceForge is unstable and frequently fails in the middle of a clone, so I switched it out for the GitHub mirror instead.
> build-mingw-w64.sh: Switch to github mirror

- build-mingw-w64-libraries.sh
- build-mingw-w64.sh
I encountered this while I was setting `CC` and `CXX` when running `build-all.sh`, which causes the mingw-w64 build to pick up the wrong compiler. This should fix the problem.
> Explicitly set CC to the correct compiler

- build-llvm.sh
`When cloning master and checking out a pinned old hash, we can't use --depth=1.`
Of course, we can :P
```console
$ du -hs llvm-project-*
1,3G    llvm-project-depth-1
2,9G    llvm-project-with-git-clone
```
PS. It's better to use pushd/popd instead of cd (easier if we need to go deeper in other scripts).
> Optimize git-checkout (use depth 1)

- build-mingw-w64-libraries.sh
- build-mingw-w64-tools.sh
- build-mingw-w64.sh
Install copyright notices into the final package. This makes LLVM MinGW
comply with many of the licenses (which require attribution), and also
makes it easier for users of LLVM MinGW to audit licenses of software
they use.
> build-mingw-w64: Install COPYING files

- install-wrappers.sh
A regular GCC install doesn't provide tools like `<triple>-{cc,c99,c11}`, so there's probably not much need to include them.
Some distributions of tools may provide tools with the unprefixed names `cc`, `c99` and `c11` though, as custom frontends or symlinks to the regular compiler. Therefore, keep the unprefixed frontends with these names.
Does this seem reasonable to others?
CC @robUx4, I have a faint memory that you might have been the one who requested that I'd provide a `c99` frontend here (in late 2018, but I didn't find the exact discussion)
CC @mati865 I think I've discussed something along these lines with you at some point too...
> install-wrappers: Don't install cross-prefixed cc/c99/c11 tools

- .github/workflows/build.yml
- Dockerfile
- Dockerfile.dev
- build-all.sh
- build-compiler-rt.sh
- build-libcxx.sh
- build-libssp.sh
- build-mingw-w64-libraries.sh
- build-mingw-w64.sh
- build-openmp.sh
- libssp-Makefile
- run-tests.sh
- test/cfguard-test.c
Adds the option to build with Control Flow Guard support. This is disabled by default and currently only enabled for the scheduled GitHub Actions build because it requires latest LLVM 16 and mingw-w64. We should change the default to enabled for the next release.
Closes https://github.com/mstorsjo/llvm-mingw/issues/301
> Add Control Flow Guard support

- build-compiler-rt.sh
- build-libcxx.sh
- build-lldb-mi.sh
- build-llvm.sh
- build-openmp.sh
this allows simplification, the functionality was added long ago to CMake.
The install can also be properly "staged" by using the `--prefix` option which might be useful.
> use CMake's build and install functionality

- build-llvm.sh
Used to enable CUDA filter support for FFmpeg without relying on another Clang.
> build-llvm: enable nvptx

- .github/workflows/build.yml
- .github/workflows/msvcrt.yml
- release-macos.sh
- release.sh
This introduces the normal practise of not storing personal uid/gid in the archives. tar does a different thing with them whether you unpack as root or another user. 
Further the timestamp variations are useless noise, the second commit will normalize timestamps used by compiler/toolchain as well as the tar archive.
> Improve tar packaging

- strip-llvm.sh
Should be pretty safe changes.
(did not want to make a separate PR for the macro update)
> Install clang-scan-deps tool

- build-llvm.sh
- install-wrappers.sh
- strip-llvm.sh
It's an equivalent to MSVC [lib.exe](https://llvm.org/docs/CommandGuide/llvm-lib.html).
It is [used by meson](https://github.com/mesonbuild/meson/blob/1e986554ef2071f59fb796cda5e66c448bde6ac9/mesonbuild/scripts/symbolextractor.py#L209) to find the DLL name from a `.lib`/`.dll.a`. The other option is dlltool, which is not the same as llvm-dlltool.
> build-llvm: Install and keep llvm-lib

- build-mingw-w64.sh
it also takes an inordinate amount of time there.
> enable --disable-dependency-tracking on CYGWIN also

- build-compiler-rt.sh
- build-mingw-w64.sh
- build-openmp.sh
Both LLVM and mingw-w64 now have sufficient ARM64EC support to build a functional toolchain. This PR adds the necessary llvm-mingw tweaks. With these changes, it's possible to build the toolchain using:
```
ARCHS="i686 x86_64 armv7 aarch64 arm64ec" LLVM_VERSION=main ./build-all.sh
```
> Add initial ARM64EC support
